application:
  port: 8000
  base_url: "http://127.0.0.1"
  hmac_secret: "s9~D(*(lqI(6HL[sG,ZhD)sv[/?+<3i~]/-Lt{!bItSdS}).Rk,AqN'GA8sg@uj"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  timeout_milliseconds: 10000
  authorization_token: "bbf6c070-ef53-4edd-b1a8-103f06b3a2e5"