application:
  port: 8000
  base_url: "http://127.0.0.1"
  hmac_secret: "f%GX6(m74Cg@SE73KX)cDCRPrQqZB^CEnFm3Y3KA9wnar!d4qFe9M7f2R)krq+r^7WPC^@CTMk+wEKzqT*Ey@@8Ww)&VN!QhsLs9IwJ)us+HSstCb32xgY9Vz3dVj4uG"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  timeout_milliseconds: 10000
  authorization_token: "bbf6c070-ef53-4edd-b1a8-103f06b3a2e5"

redis_uri: "redis://127.0.0.1:6379"
