application:
  port: 8000

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  timeout_milliseconds: 10000
  authorization_token: "7f1e52cd-086e-41d4-9c82-94b4b6a3398b"